### ISSUE TITLE
PDFを解析してCSVを作るスクリプトを書く

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/data#1]
データの更新を自動化したいので，そのためにまずPDFを解析してCSVを作るスクリプトを書きたい
実現可能性はこれから検討する

言語は，エコシステムが豊富なGolangを採用する (@shmokmt の提案)

**Comment by shmokmt** [comment]
Pythonでもやりやすいみたいですが、Netlify FunctionsはPythonのランタイムがないみたいです。
日本語のテキストがちゃんと抽出できるかは結構ハマりどころ感あります。

**Comment by shmokmt** [comment]
@nojiri1098 
[大分県と連携し、CSVでデータを提供していただく形](https://github.com/covid19-oita/covid19/issues/61#issuecomment-608263464)になったのでこのissueはクローズします
