### ISSUE TITLE
CSVの取得先をオープンデータに変更する

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/data#12]
patient.csv
http://data.bodik.jp/dataset/f632f467-716c-46aa-8838-0d535f98b291/resource/3714d264-70f3-4518-a57a-8391e0851d7d/download/440001oitacovid19patients.csv

data_summary.csv
http://data.bodik.jp/dataset/f632f467-716c-46aa-8838-0d535f98b291/resource/96440e66-3061-43d6-adf3-ef1f24211d3a/download/440001oitacovid19datasummary.csv

ダウンロードして `/csv` に保存するかどうか🤔

**Comment by nojiri1098** [comment]
CSV が古くて development をmaster にマージできないので，こちらを優先していただけると助かります

**Comment by varusan** [comment]
https://github.com/covid19-oita/data/commit/345e2b34a074abbfcbb85b28874cf934630741f0
このコミットで新しいCSVには入れ替えております。
