### ISSUE TITLE
READMEから確認URLを削除する

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/data#13]
Netlifyはすでに削除しています
productionブランチに関する記述もいりません

covid19 のサブモジュールであることを明記してもいいかもしれないですね

**Comment by shmokmt** [comment]
> Netlifyはすでに削除しています
productionブランチに関する記述もいりません

@nojiri1098 
なのであれば、リモートブランチ1本だけにしてそれ以外消してしまっても良いですか？  👀

**Comment by nojiri1098** [comment]
@shmokmt 
development と master 以外は消していいです
