### ISSUE TITLE
master の GitHub Actions が失敗する

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/data#18]
https://github.com/covid19-oita/data/actions/runs/70321645
![スクリーンショット 2020-04-04 11 53 53](https://user-images.githubusercontent.com/24912801/78417226-070b9800-766b-11ea-82aa-695a603c649d.png)

**Comment by varusan** [comment]
nothing to commit がexit code 1で返えるからエラーになってしまっている…？

**Comment by varusan** [comment]
https://github.com/covid19-oita/data/runs/559835603?check_suite_focus=true
Retryしたらうまくいった🧐

**Comment by varusan** [comment]
`master`はdevelopmentのデータが反映されればいいので、commit & pushは必要ないですか？

**Comment by nojiri1098** [comment]
@varusan はい，消しておいてください
