### ISSUE TITLE
患者が発生していない日でも当日のデータを生成したい

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/data#27]
4月5日 22:05 に更新したときの画像です

4月5日は1人も患者が出ていないにもかかわらず，右上に「1人」と表示されています．よく見れば4月4日の人数であることはわかりますが，誤解されかねません．

4月5日にPythonスクリプトを実行した場合，患者がいなくても実行した時刻における4月5日のデータが含まれるようにしたいです．

![スクリーンショット 2020-04-05 22 17 40](https://user-images.githubusercontent.com/24912801/78499404-737db880-778b-11ea-906f-8ed62ff0c35f.png)

**変更前**
```
        ...

        {
          "日付": "2020-04-03",
          "小計": 1
        },
        {
          "日付": "2020-04-04",
          "小計": 1
        }
      ]
    },
```

**変更後**
```
        ...

        {
          "日付": "2020-04-03",
          "小計": 1
        },
        {
          "日付": "2020-04-04",
          "小計": 1
+       },
+       {
+         "日付": "2020-04-05",
+         "小計": 0
        }
      ]
    },
```

**Comment by varusan** [comment]
まだデータがない状態を”0”とするかどうかを考えたいです。

データのない状態を0にするかどうかを実装時にも悩んでいて、
画面では4/4時点での実績値であると明記されるため、データのない状態を含めない方針にしました。

**Comment by nojiri1098** [comment]
@varusan 
その気持ちはわかります．でも，22:00となると当日分のデータが公表されている時間なので，患者がいれば4月5日の実績値になっていますよね．それなのに，患者がいないときだけ実績値が更新されないというのは違和感があります．

**Comment by varusan** [comment]
それでは「22:00以降にデータがない場合は0にする」とするのはどうでしょうか。
22:00でなくてもっと早くても良いかと思いますが。

**Comment by nojiri1098** [comment]
@varusan 
それがいいと思います🙆‍♂ 
前回，大分県のCSVが更新されたのが21:00くらいだったので，とりあえず22:00以降にしましょう
