### ISSUE TITLE
患者が発生していない場合に実績値の日付が更新されない

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/data#28]
4月6日 9:35 に更新したときの画像です

4月6日になったにもかかわらず，実績値が4月4日のものになっています．4月5日に患者がいなかったことが原因だと思われます．

これでは，患者が発生しなかった日が連続した場合，いつまでも4月4日の実績値が表示されることになります．患者が発生したかどうかにかかわらず，前日の実績値が表示されるようにしたいです．

![スクリーンショット 2020-04-06 9 36 17](https://user-images.githubusercontent.com/24912801/78514397-19610f80-77ec-11ea-86cd-51e0821eab69.png)

**Comment by varusan** [comment]
#27 と併せて対応します
