### ISSUE TITLE
データ更新時にrepository dispatch eventで通知する仕組みを作る

### ISSUE THREAD

**Issue by varusan** [covid19-oita/data#4]
データ更新時のワークフロー
- covid19-oita/data、csv を手動更新
- covid19-oita/data、data.json を生成して自動コミット
- covid19-oita/data、covid19-oita/covid19 に repository_dispatch で通知
- covid19-oita/covid19、通知を受けてサブモジュールを更新 -> master と development をデプロイ

**Comment by nojiri1098** [comment]
https://github.com/covid19-oita/covid19/issues/159 により不要になりました
