### ISSUE TITLE
CIに失敗した時にSlackに通知する

### ISSUE THREAD

**Issue by varusan** [covid19-oita/data#44]
WebHookを使ってSlackのchannelに通知する

**Comment by varusan** [comment]
dataがUpdateされた時にも通知されるようにしたい

**Comment by shmokmt** [comment]
@varusan 
> dataがUpdateされた時にも通知されるようにしたい

こちらはSlackのGitHubアプリでリポジトリのcommitsだけをsubscribeするようにしようと思います。
