### ISSUE TITLE
大分県オープンデータカタログサイトのcsvのデータが最新でない

### ISSUE THREAD

**Issue by varusan** [covid19-oita/data#45]
大分県オープンデータカタログサイトのCSVデータが最新でない時がある
- https://data.bodik.jp/dataset/f632f467-716c-46aa-8838-0d535f98b291/resource/3714d264-70f3-4518-a57a-8391e0851d7d/download/440001oitacovid19patients.csv
- https://data.bodik.jp/dataset/f632f467-716c-46aa-8838-0d535f98b291/resource/96440e66-3061-43d6-adf3-ef1f24211d3a/download/440001oitacovid19datasummary.csv

**Comment by varusan** [comment]
CSVにない抜けた日付のデータをPDFからとってきておぎなうという方針を検討中。

**Comment by nojiri1098** [comment]
県のオープンデータがPDFよりも早く更新されるようになったので対応しなくてよくなりました
