### ISSUE TITLE
相談件数，データが存在する最新の日付を実績値の日付とする

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/data#55]
相談件数は数日遅れで更新されることが多いので，現状では実績値が0件になることが多い．

たとえば以下の場合，(右端が相談件数)
実際は発表されていないだけにもかかわらず，4月16日の相談件数が0件と表示されてしまう．
![image](https://user-images.githubusercontent.com/24912801/79522824-ada65e80-8097-11ea-81ed-6fa8f6b9d1a5.png)

そこで，相談件数だけは発表されているデータだけを表示するようにしたい
たとえば先ほどの例であれば，今日が４月１７日であっても４月１５日のデータを実績値として表示する (現状では４月１６日の実績値が0件と表示される)

更新日時については変更する必要がないと考えています
その日のデータがあるかどうかにかかわらず，CSVは更新日時時点での最新データなので (議論の余地はあります)

**Comment by satetsu** [comment]
> 更新日時については変更する必要がないと考えています
> その日のデータがあるかどうかにかかわらず，CSVは更新日時時点での最新データなので (議論の余地はあります)

「更新日時」という観点では上記で同意です。
ただ、表示されている数字は「何月何日のデータです」という説明は必要です。これは分離して検討する必要があるでしょう。

**Comment by satetsu** [comment]
訂正です。
現状、「Y/M 実績値」と表記がありますね。これがデータがある最新日付になっていれば問題ありません。

**Comment by varusan** [comment]
https://github.com/covid19-oita/data/blob/master/tool/convert/modules/DataHandler.py#L13
https://github.com/covid19-oita/data/blob/master/tool/convert/modules/DataHandler.py#L55

patients.dataの値ですが、現在は上記のようにデータを生成した時刻が入るようになっています。
この値をdata_summary.csvの相談件数がある最後の日を入れるようにします。
