### ISSUE TITLE
CSVの年代カラムに「学生」や「生徒」が入力されている

### ISSUE THREAD

**Issue by varusan** [covid19-oita/data#60]
参考: https://github.com/covid19-oita/data/blob/master/csv/440001oitacovid19patients.csv#L58

のように年代カラムに「学生」や「生徒」と表記されているため、
「年代別陽性患者数」と「陽性患者数」の数値にずれが生じている

**Comment by varusan** [comment]
@satetsu さんより

### 仕様1
［生徒は10代、学生は20代に読み替える］
生徒は中高生、学生は大学生という定義があります
懸念点：「10代の大学生」も存在するので実年代との矛盾が発生することもある
懸念点：表記の揺れが多発して読み替えパターンが増える
懸念点：非公開情報なのにデータでは公開情報になっていると誤解される

### 仕様2
［非公開情報はデータを空欄にする］
データ作成時にデータを空欄にしてもらう
データ空欄は「非公開」と表示する処理の追加
「年代別陽性患者数」に年代非公開時の処理を追加

**Comment by satetsu** [comment]
仕様2で問題なしであれば、県に伝えます。

**Comment by varusan** [comment]
仕様２のほうで実装を進めます
